Removed wildcard deduplication using set
adieyal/dynamicprompts pull request #91
Opened 2023-06-03 20:21 UTC by adieyal

This allows the wildcardmanager to decide whether the collection should be deduplicated or not.

2023-06-03 22:09 UTC, akx approved these changes

2023-06-03 22:10 UTC, akx approved these changes
LGTM, but other tests need adjustment because there's a new file in the test wildcards root. You could move the new test file out of there because it's pretty separate.

2023-06-05 19:17 UTC, akx requested changes
(so yeah, tests fail, lgtm otherwise)

2023-07-14 19:39 UTC, adieyal commented
Closing since it has been merged here: 0d0b524bc7b8e2dc83998915cd7599034ed028a5

2023-07-14 19:39 UTC, closed without merging