Added an option for wildcards to be shuffled
adieyal/dynamicprompts pull request #94
Opened 2023-07-14 21:46 UTC by adieyal

This will allow combinatorial generations to be random which matters when the number of generations is limited. This only solves the problem when wildcards are used. Inline choice operators are still deterministic

2023-07-14 21:48 UTC, adieyal commented
This PR aims to address https://github.com/adieyal/sd-dynamic-prompts/issues/328
A config option will be available in the settings tab to enable shuffling.

2023-07-17 09:56 UTC, akx requested changes

2023-07-17 09:56 UTC, akx commented on src/dynamicprompts/wildcards/wildcard_manager.py
> +        Caching disabled if wildcard manager is configured to shuffle wildcards.
I think it'd be better to just keep caching things, but shuffle a copy of `list_values` just before returning it from here?

2023-07-18 12:27 UTC, akx requested changes

2023-07-18 17:25 UTC, akx requested changes

2023-07-18 17:25 UTC, akx commented on src/dynamicprompts/wildcards/wildcard_manager.py
> +    def get_all_values(self, wildcard: str):
Sorry 😅 
```suggestion
    def get_all_values(self, wildcard: str) -> list[str]:
```

2023-07-18 17:26 UTC, merged